### ISSUE TITLE
How do I change condition value to enable reflective prompt

### ISSUE THREAD

**Issue by ssaket** [RationalityEnhancementGroup/ReflectiveLearning#1]
Thank you for your work and for making the source code public.

I am new to psiTurk and am trying to run the experiment locally on my windows laptop using WSL (Ubuntu 22 LTS). I want to change the `condition` value to see reflective prompts (i.e. `condition = 2`). However, when I update its value and restart my psiTurk server, I still see the old code in debug window (DEV TOOLS). I tried updating `condition` value at, (1) [Experiment/static/js/setup.js : L24](https://github.com/RationalityEnhancementGroup/ReflectiveLearning/blob/554a6b7adc690ec3a8cd91b086752a2fa77df4a8/Experiment/static/js/setup.js#L24), (2) [Experiment/static/js/experiment.js: L29, (3) L23](https://github.com/RationalityEnhancementGroup/ReflectiveLearning/blob/554a6b7adc690ec3a8cd91b086752a2fa77df4a8/Experiment/static/js/experiment.js#L29) and my config.txt looks like 

```shell
[Server Parameters]
host = localhost
port = 22362

[Task Parameters]
experiment_code_version = 1.0
condition = 2
num_counters = 2

[Shell Parameters]
launch_in_sandbox_mode = true
```

I also added some dummy `console.log` statements, but even that does not show up in dev tools console. Could you tell me what am I doing wrong here and why the psiTurk server is not picking up new changes in javascript files?

**Comment by vmfelso** [comment]
Hi, if you just want to see a particular condition, I think you should be fine if you manually change the CONDITION variable around line 29 of experiment.js like you tried, for example:

```
CONDITION = 2
console.log(`MANUAL CONDITION: ${CONDITION}.`);
```

Since you also couldn't see attempts to log to the console: 
- Here are the psiturk docs on restarting the psiturk server if there was a misunderstanding there: https://psiturk.readthedocs.io/en/latest/command_line.html#server-restart 
- Perhaps you also need to do a hard refresh in your browser since this is in the `/static` directory.

I hope that helps!

**Comment by ssaket** [comment]
Hi @vmfelso, Extremely sorry for the late response, I was busy with another task.  I've figured out the problem - there was an issue with my setup, and it is fixed now.  So, I will close this issue. Thank you so much!
